### Importing packages

In [75]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import matplotlib.style as styple
import seaborn as sns
import datetime as dt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import ExtraTreeClassifier

In [2]:
# Reading csv files
bitcoin = pd.read_csv('coin_Bitcoin.csv')
HF = pd.read_csv('heart_failure_clinical_records_data.csv')

In [3]:
pd.set_option('display.max_columns', None)
bitcoin.head()

SNo     Name Symbol                 Date        High         Low  \
0    1  Bitcoin    BTC  2013-04-29 23:59:59  147.488007  134.000000   
1    2  Bitcoin    BTC  2013-04-30 23:59:59  146.929993  134.050003   
2    3  Bitcoin    BTC  2013-05-01 23:59:59  139.889999  107.720001   
3    4  Bitcoin    BTC  2013-05-02 23:59:59  125.599998   92.281898   
4    5  Bitcoin    BTC  2013-05-03 23:59:59  108.127998   79.099998   

         Open       Close  Volume     Marketcap  
0  134.444000  144.539993     0.0  1.603769e+09  
1  144.000000  139.000000     0.0  1.542813e+09  
2  139.000000  116.989998     0.0  1.298955e+09  
3  116.379997  105.209999     0.0  1.168517e+09  
4  106.250000   97.750000     0.0  1.085995e+09

In [4]:
bitcoin.shape

(2991, 10)

In [5]:
bitcoin.Name.unique()

array(['Bitcoin'], dtype=object)

In [6]:
bitcoin.Symbol.unique()

array(['BTC'], dtype=object)

In [7]:
# Dropping 'SNo' column
bitcoin.drop(['SNo'], axis=1, inplace=True)

In [8]:
# Dropping 'Symbol' column
bitcoin.drop(['Symbol'], axis=1, inplace=True)

In [9]:
bitcoin.columns

Index(['Name', 'Date', 'High', 'Low', 'Open', 'Close', 'Volume', 'Marketcap'], dtype='object')

In [10]:
HF.head()

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0  75.0        0                       582         0                 20   
1  55.0        0                      7861         0                 38   
2  65.0        0                       146         0                 20   
3  50.0        1                       111         0                 20   
4  65.0        1                       160         1                 20   

   high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    1  265000.00               1.9           130    1   
1                    0  263358.03               1.1           136    1   
2                    0  162000.00               1.3           129    1   
3                    0  210000.00               1.9           137    1   
4                    0  327000.00               2.7           116    0   

   smoking  time  DEATH_EVENT  
0        0     4            1  
1        0     6            1  
2        1     7            1  
3        0     7            1  
4        0     8            1

In [11]:
HF.columns

Index(['age', 'anaemia', 'creatinine_phosphokinase', 'diabetes',
       'ejection_fraction', 'high_blood_pressure', 'platelets',
       'serum_creatinine', 'serum_sodium', 'sex', 'smoking', 'time',
       'DEATH_EVENT'],
      dtype='object')

In [12]:
HF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   age                       299 non-null    float64
 1   anaemia                   299 non-null    int64  
 2   creatinine_phosphokinase  299 non-null    int64  
 3   diabetes                  299 non-null    int64  
 4   ejection_fraction         299 non-null    int64  
 5   high_blood_pressure       299 non-null    int64  
 6   platelets                 299 non-null    float64
 7   serum_creatinine          299 non-null    float64
 8   serum_sodium              299 non-null    int64  
 9   sex                       299 non-null    int64  
 10  smoking                   299 non-null    int64  
 11  time                      299 non-null    int64  
 12  DEATH_EVENT               299 non-null    int64  
dtypes: float64(3), int64(10)
memory usage: 30.5 KB


In [13]:
bitcoin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2991 entries, 0 to 2990
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Name       2991 non-null   object 
 1   Date       2991 non-null   object 
 2   High       2991 non-null   float64
 3   Low        2991 non-null   float64
 4   Open       2991 non-null   float64
 5   Close      2991 non-null   float64
 6   Volume     2991 non-null   float64
 7   Marketcap  2991 non-null   float64
dtypes: float64(6), object(2)
memory usage: 187.1+ KB


In [14]:
bitcoin.describe()

High           Low          Open         Close        Volume  \
count   2991.000000   2991.000000   2991.000000   2991.000000  2.991000e+03   
mean    6893.326038   6486.009539   6700.146240   6711.290443  1.090633e+10   
std    11642.832456  10869.032130  11288.043736  11298.141921  1.888895e+10   
min       74.561096     65.526001     68.504997     68.431000  0.000000e+00   
25%      436.179001    422.879486    430.445496    430.569489  3.036725e+07   
50%     2387.610107   2178.500000   2269.889893   2286.409912  9.460360e+08   
75%     8733.926948   8289.800459   8569.656494   8576.238715  1.592015e+10   
max    64863.098908  62208.964366  63523.754869  63503.457930  3.509679e+11   

          Marketcap  
count  2.991000e+03  
mean   1.208761e+11  
std    2.109438e+11  
min    7.784112e+08  
25%    6.305579e+09  
50%    3.741503e+10  
75%    1.499957e+11  
max    1.186364e+12

In [17]:
# Extract date and time information from 'Date' column
bitcoin['Date'] = pd.to_datetime(bitcoin['Date'])
bitcoin['Date_year'] = bitcoin['Date'].dt.year
bitcoin['Date_month'] = bitcoin['Date'].dt.month
bitcoin['Date_day'] = bitcoin['Date'].dt.day
bitcoin['Date_hour'] = bitcoin['Date'].dt.hour
bitcoin['Date_minute'] = bitcoin['Date'].dt.minute
bitcoin['Date_second'] = bitcoin['Date'].dt.second

In [18]:
# drop 'Date' column as it is no longer needed
bitcoin.drop(['Date'], axis=1, inplace=True)

In [19]:
bitcoin.head()

Name        High         Low        Open       Close  Volume  \
0  Bitcoin  147.488007  134.000000  134.444000  144.539993     0.0   
1  Bitcoin  146.929993  134.050003  144.000000  139.000000     0.0   
2  Bitcoin  139.889999  107.720001  139.000000  116.989998     0.0   
3  Bitcoin  125.599998   92.281898  116.379997  105.209999     0.0   
4  Bitcoin  108.127998   79.099998  106.250000   97.750000     0.0   

      Marketcap  Date_year  Date_month  Date_day  Date_hour  Date_minute  \
0  1.603769e+09       2013           4        29         23           59   
1  1.542813e+09       2013           4        30         23           59   
2  1.298955e+09       2013           5         1         23           59   
3  1.168517e+09       2013           5         2         23           59   
4  1.085995e+09       2013           5         3         23           59   

   Date_second  
0           59  
1           59  
2           59  
3           59  
4           59

### Features and Target Variables

In [20]:
X = bitcoin.drop(['Marketcap'], axis=1)
y = bitcoin['Marketcap']
X.head()

Name        High         Low        Open       Close  Volume  Date_year  \
0  Bitcoin  147.488007  134.000000  134.444000  144.539993     0.0       2013   
1  Bitcoin  146.929993  134.050003  144.000000  139.000000     0.0       2013   
2  Bitcoin  139.889999  107.720001  139.000000  116.989998     0.0       2013   
3  Bitcoin  125.599998   92.281898  116.379997  105.209999     0.0       2013   
4  Bitcoin  108.127998   79.099998  106.250000   97.750000     0.0       2013   

   Date_month  Date_day  Date_hour  Date_minute  Date_second  
0           4        29         23           59           59  
1           4        30         23           59           59  
2           5         1         23           59           59  
3           5         2         23           59           59  
4           5         3         23           59           59

In [26]:
# Drop 'Name' column since it is non-numeric data 
# Not suitable for linear regression model
X = bitcoin.drop('Name', axis=1)

### Linear Regression

In [27]:
Lr = LinearRegression()

### Train-Test-Split

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

Lr.fit(X_train, y_train)

LinearRegression()

### Prediction

In [29]:
y_pred = Lr.predict(X_test)
y_pred

array([3.92719247e+09, 4.61426469e+09, 4.28637588e+10, 1.35589384e+11,
       9.08931293e+09, 5.85805988e+09, 1.36460398e+10, 6.49953674e+09,
       9.71611626e+11, 6.92716170e+09, 5.77055097e+09, 3.56223831e+09,
       7.24455889e+10, 1.01465006e+09, 1.04975276e+10, 1.36504884e+11,
       2.14082402e+11, 3.20174319e+11, 1.58465056e+11, 1.17050623e+11,
       1.01620291e+10, 4.50377971e+10, 1.47525141e+11, 3.67342555e+10,
       6.90023773e+09, 1.80804860e+11, 8.86991864e+09, 1.82738948e+11,
       5.08979928e+09, 4.73883348e+10, 1.04294602e+12, 1.03408819e+10,
       6.36943945e+10, 6.85745793e+10, 1.06995041e+10, 1.55114132e+11,
       3.81586777e+10, 9.23484570e+09, 3.85988813e+09, 1.84443441e+11,
       1.79119158e+10, 4.65698822e+09, 3.77804902e+09, 1.14186840e+11,
       1.31571001e+09, 1.22174009e+11, 6.28466643e+09, 1.28970221e+11,
       1.11134755e+11, 6.62072376e+09, 3.23293833e+09, 7.00171275e+09,
       1.08448410e+11, 2.60530780e+10, 1.91657204e+11, 1.22978749e+11,
      

In [30]:
# Create a DataFrame for real_value and pred_value
print(pd.DataFrame({'real_value': y_test, 'pred_value': y_pred}))

        real_value    pred_value
905   3.927192e+09  3.927192e+09
557   4.614265e+09  4.614265e+09
1529  4.286376e+10  4.286376e+10
1811  1.355894e+11  1.355894e+11
1217  9.089313e+09  9.089313e+09
...            ...           ...
266   1.069445e+10  1.069445e+10
2192  9.457383e+10  9.457383e+10
528   4.878719e+09  4.878719e+09
2465  1.702056e+11  1.702056e+11
2903  1.116890e+12  1.116890e+12

[599 rows x 2 columns]


### Mean Absolute Error

In [31]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_pred)

8.95801092030011e-05

In [32]:
Lr.score(X_test, y_test)

1.0

### Lasso Regression

In [33]:
from sklearn.linear_model import Lasso

Ls = Lasso()

Ls.fit(X_train, y_train)

y_pred = Ls.predict(X_test)

Ls.score(X_test, y_test)

C:\Users\owner\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.172e+22, tolerance: 1.050e+22
  model = cd_fast.enet_coordinate_descent(


0.9997765423409939

In [34]:
mean_absolute_error(y_test, y_pred)

2073612716.285832

### Decision Tree Regressor

In [41]:
from sklearn.tree import DecisionTreeRegressor

tree = DecisionTreeRegressor(max_depth=1)

tree.fit(X_train, y_train)

y_tree_pred = tree.predict(X_test)

tree.score(X_test, y_test)

0.828969245921702

In [39]:
# Compare using the max_depth to 5
tree = DecisionTreeRegressor(max_depth=5)

tree.fit(X_train, y_train)

y_tree_pred = tree.predict(X_test)

tree.score(X_test, y_test)

0.9990206393879496

In [40]:
mean_absolute_error(y_test, y_tree_pred)

4535925153.361078

### Classification

In [42]:
HF.head()

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0  75.0        0                       582         0                 20   
1  55.0        0                      7861         0                 38   
2  65.0        0                       146         0                 20   
3  50.0        1                       111         0                 20   
4  65.0        1                       160         1                 20   

   high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    1  265000.00               1.9           130    1   
1                    0  263358.03               1.1           136    1   
2                    0  162000.00               1.3           129    1   
3                    0  210000.00               1.9           137    1   
4                    0  327000.00               2.7           116    0   

   smoking  time  DEATH_EVENT  
0        0     4            1  
1        0     6            1  
2        1     7            1  
3        0     7            1  
4        0     8            1

In [43]:
# Features and target variables for HR dataset
X = HF.drop(['DEATH_EVENT'], axis=1)
y = HF['DEATH_EVENT']

In [44]:
X.columns

Index(['age', 'anaemia', 'creatinine_phosphokinase', 'diabetes',
       'ejection_fraction', 'high_blood_pressure', 'platelets',
       'serum_creatinine', 'serum_sodium', 'sex', 'smoking', 'time'],
      dtype='object')

In [45]:
# Check for total missing values
X.isnull().sum()

age                         0
anaemia                     0
creatinine_phosphokinase    0
diabetes                    0
ejection_fraction           0
high_blood_pressure         0
platelets                   0
serum_creatinine            0
serum_sodium                0
sex                         0
smoking                     0
time                        0
dtype: int64

In [46]:
y.isnull().sum()

0

In [47]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   age                       299 non-null    float64
 1   anaemia                   299 non-null    int64  
 2   creatinine_phosphokinase  299 non-null    int64  
 3   diabetes                  299 non-null    int64  
 4   ejection_fraction         299 non-null    int64  
 5   high_blood_pressure       299 non-null    int64  
 6   platelets                 299 non-null    float64
 7   serum_creatinine          299 non-null    float64
 8   serum_sodium              299 non-null    int64  
 9   sex                       299 non-null    int64  
 10  smoking                   299 non-null    int64  
 11  time                      299 non-null    int64  
dtypes: float64(3), int64(9)
memory usage: 28.2 KB


In [48]:
# checking summary statistic
X.describe()

age     anaemia  creatinine_phosphokinase    diabetes  \
count  299.000000  299.000000                299.000000  299.000000   
mean    60.833893    0.431438                581.839465    0.418060   
std     11.894809    0.496107                970.287881    0.494067   
min     40.000000    0.000000                 23.000000    0.000000   
25%     51.000000    0.000000                116.500000    0.000000   
50%     60.000000    0.000000                250.000000    0.000000   
75%     70.000000    1.000000                582.000000    1.000000   
max     95.000000    1.000000               7861.000000    1.000000   

       ejection_fraction  high_blood_pressure      platelets  \
count         299.000000           299.000000     299.000000   
mean           38.083612             0.351171  263358.029264   
std            11.834841             0.478136   97804.236869   
min            14.000000             0.000000   25100.000000   
25%            30.000000             0.000000  212500.000000   
50%            38.000000             0.000000  262000.000000   
75%            45.000000             1.000000  303500.000000   
max            80.000000             1.000000  850000.000000   

       serum_creatinine  serum_sodium         sex    smoking        time  
count         299.00000    299.000000  299.000000  299.00000  299.000000  
mean            1.39388    136.625418    0.648829    0.32107  130.260870  
std             1.03451      4.412477    0.478136    0.46767   77.614208  
min             0.50000    113.000000    0.000000    0.00000    4.000000  
25%             0.90000    134.000000    0.000000    0.00000   73.000000  
50%             1.10000    137.000000    1.000000    0.00000  115.000000  
75%             1.40000    140.000000    1.000000    1.00000  203.000000  
max             9.40000    148.000000    1.000000    1.00000  285.000000

### Train-Test-Split

In [49]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

### Support Vector Machines

In [51]:
svm = svm.SVC()

svm.fit(X_train, y_train)

SVC()

In [52]:
y_pred = svm.predict(X_test)

In [53]:
svm.score(X_test, y_test)

0.5666666666666667

In [54]:
mean_absolute_error(y_test, y_pred)

0.43333333333333335

### Logistic Regression

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [57]:
LGR = LogisticRegression()

LGR.fit(X_train, y_train)

LogisticRegression()

In [58]:
y_pred = LGR.predict(X_test)

In [59]:
LGR.score(X_test, y_test)

0.85

In [60]:
mean_absolute_error(y_test, y_pred)

0.15

### KNeighborsClassifier

In [62]:
KNN = KNeighborsClassifier()

KNN.fit(X_train, y_train)

KNeighborsClassifier()

In [63]:
KNN.predict(X_test)

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [64]:
KNN.score(X_test, y_test)

0.55

### Naive Bayes Classifier

In [68]:
gnb = GaussianNB()

y_pred = gnb.fit(X_train, y_train).predict(X_test)

y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1], dtype=int64)

In [69]:
gnb.score(X_test, y_test)

0.85

In [70]:
mean_absolute_error(y_test, y_pred)

0.15

### Decision Tree Classifier

In [72]:
my_tree = DecisionTreeClassifier(max_depth=8)

my_tree.fit(X_train, y_train)

y_pred = my_tree.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1], dtype=int64)

In [73]:
my_tree.score(X_test, y_test)

0.65

In [74]:
mean_absolute_error(y_test, y_pred)

0.35

### Extra Tree Classifier

In [76]:
extree = ExtraTreeClassifier()

extree.fit(X_train, y_train)

y_pred = extree.predict(X_test)

y_pred

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0], dtype=int64)

In [77]:
extree.score(X_test, y_test)

0.7

In [78]:
mean_absolute_error(y_test, y_pred)

0.3